version: "3.9"

services:
  ubuntu-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-ssh-server
    restart: unless-stopped
    environment:
      - TZ=Europe/Helsinki
    ports:
      - "2222:22"      # host 2222 -> container 22
    volumes:
      - .:/workspace    # mount current folder into /workspace
      - ssh_host_keys:/etc/ssh   # persist SSH host keys
    tty: true
    stdin_open: true

volumes:
  ssh_host_keys:
